### ISSUE TITLE
Feature request: Select device on launch?

### ISSUE THREAD

**Issue by sti3** [erik/lastcast#32]
I added all my chromecast devices in my initial configuration but one of them, a portable speaker, isn't always on. When it's off, the application fails with "Failed to connect! Exiting" and tries again to launch after a restart.

What would be great is if the application didn't exit if it couldn't find a device OR if you could manually select a CC device with a flag on launch.

**Comment by erik** [comment]
Thanks for the feature request!

I started implementing retry logic (in #33) so that lastcast can continually try to connect to devices without failing. Need to do some more testing before I merge that in.

I decided to go that route instead of the command line flag because lastcast is intended to be a long running process, and it would be kind of lousy to remember to restart it with the proper flag every time you turn on your speaker. 

Let me know if you have any feedback!

**Comment by sti3** [comment]
Works for me as long as that continual retrying doesn't introduce any
instability.

Aaron

**Comment by erik** [comment]
Yeah... that's the reason I've been waiting a couple days to merge. 

Seems like continually retrying connections exposes some underlying bugs in pychromecast. I'll keep playing with it some more, and if I can't get it completely stable I'll swap the PR over to implementing an `ignore_missing` config flag, which is more in line with your original request.

**Comment by erik** [comment]
Hi @sti3, sorry about the delay there!

Just released `lastcast==0.6.0`, which includes new config options `retry_missing` and `ignore_missing`.

I've been testing `retry_missing` on my home network and it seems stable, but I'm not convinced it's 100% there yet. `ignore_missing` should be fine though!

Please let me know if you run into any issues with either feature.
